name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: get python
        uses: actions/setup-python@v2
      - name: get conan
        uses: turtlebrowser/get-conan@main
      - name: build
        run: ./ci/ci.bash
        shell: bash
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: godot-steamp-api-${{ matrix.os }}
          path: work/install
  
  package:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download all build artifacts
        uses: actions/download-artifact@v2

  remove-old-artifacts:
    needs: [package]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: remove-old-artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '10 minutes'
